#!/usr/bin/env node
/**
 * generate-page.js — F4 + N9: Generate real React component tree in page.tsx
 *
 * F4 (NEW): Bỏ dangerouslySetInnerHTML — dùng real React component tree
 *   - Trước đây: page.tsx = `fs.readFileSync(html) + dangerouslySetInnerHTML`
 *   - Bây giờ: page.tsx = imports {Header, HeroSection, MainContent, Footer} + composes
 *   - Lợi ích: React tree thực sự, có thể customize per-component, hot-reload nhanh hơn
 *
 * N9 (NEW): Real React component tree
 *   - Mỗi component từ components-raw/ → ported sang src/components/pages/{page}/
 *   - page.tsx imports và compose các components này
 *   - Layout: <Header/> + <MainContent/> + <Footer/>
 *
 * Output:
 *   - src/app/{route}/page.tsx — Next.js App Router page that imports real components
 *
 * Usage:
 *   node generate-page.js <components-dir> <output-page.tsx> --page <slug> [--route <path>]
 *
 * Examples:
 *   node generate-page.js src/components/pages/home src/app/page.tsx --page home --route /
 *   node generate-page.js src/components/pages/about src/app/about/page.tsx --page about --route /about
 */

const fs = require('fs');
const path = require('path');

function main() {
  const args = process.argv.slice(2);
  if (args.length < 2) {
    console.error(`Usage: node generate-page.js <components-dir> <output-page.tsx> --page <slug> [--route <path>]

Examples:
  node generate-page.js src/components/pages/home src/app/page.tsx --page home --route /
  node generate-page.js src/components/pages/about src/app/about/page.tsx --page about --route /about
`);
    process.exit(1);
  }

  const componentsDir = path.resolve(args[0]);
  const outputPagePath = path.resolve(args[1]);
  const pageIdx = args.indexOf('--page');
  const routeIdx = args.indexOf('--route');

  const pageSlug = pageIdx > -1 && args.length > pageIdx + 1 ? args[pageIdx + 1] : 'unknown';
  const routePath = routeIdx > -1 && args.length > routeIdx + 1 ? args[routeIdx + 1] : `/${pageSlug}`;

  if (!fs.existsSync(componentsDir)) {
    console.error(`✖ Components dir not found: ${componentsDir}`);
    process.exit(1);
  }

  // ─── 1. Discover component files ───────────────────────────────────
  const componentFiles = fs.readdirSync(componentsDir)
    .filter(f => f.endsWith('.tsx') && f !== 'Page.tsx' && f !== 'PageFaithful.tsx')
    .map(f => f.replace('.tsx', ''));

  if (componentFiles.length === 0) {
    console.error(`✖ No component .tsx files found in ${componentsDir}`);
    process.exit(1);
  }

  console.log(`\n📄 N9: Generating page.tsx with real React component tree`);
  console.log(`   Components dir: ${componentsDir}`);
  console.log(`   Output: ${outputPagePath}`);
  console.log(`   Components: ${componentFiles.length} (${componentFiles.join(', ')})`);

  // ─── 2. Determine component order (Header first, Footer last) ─────
  const order = ['Header', 'Navbar', 'MainContent', 'HeroSection', 'HeroSlider', 'Banner', 'Carousel', 'FeaturesGrid', 'ServicesSection', 'AboutSection', 'TeamSection', 'Testimonials', 'Reviews', 'PricingSection', 'CTASection', 'ContactSection', 'FAQSection', 'StatsSection', 'BlogSection', 'Gallery', 'VideoSection', 'MapSection', 'Sidebar', 'Footer'];
  const ordered = [];
  for (const name of order) {
    if (componentFiles.includes(name)) ordered.push(name);
  }
  // Add any remaining components (e.g. custom-named sections)
  for (const name of componentFiles) {
    if (!ordered.includes(name)) ordered.push(name);
  }

  console.log(`   Render order: ${ordered.join(' → ')}`);

  // ─── 3. Generate page.tsx ─────────────────────────────────────────
  // Use relative import path from outputPagePath to componentsDir
  const relPath = path.relative(path.dirname(outputPagePath), componentsDir);
  const importPath = relPath.startsWith('.') ? relPath : './' + relPath;

  const imports = ordered
    .map(name => `import ${name} from '${importPath}/${name}';`)
    .join('\n');

  const jsx = ordered
    .map(name => `      <${name} />`)
    .join('\n');

  const pageCode = `// Auto-generated by clone-website/scripts/phase2-faithful/generate-page.js
// Real React component tree (F4: no dangerouslySetInnerHTML, N9: imports real components)

${imports}

export const metadata = {
  title: '${pageSlug}',
  description: 'Cloned page from rawline.framer.website (Mode Faithful)',
};

export default function Page() {
  return (
    <main data-page="${pageSlug}">
${jsx}
    </main>
  );
}
`;

  fs.mkdirSync(path.dirname(outputPagePath), { recursive: true });
  fs.writeFileSync(outputPagePath, pageCode, 'utf-8');

  console.log(`\n✅ Generated ${outputPagePath}`);
  console.log(`   ${ordered.length} components imported and composed`);
  console.log(`   Each component is a real React component (not HTML blob)`);
  console.log(`\n   💡 Run dev server to see your cloned page:`);
  console.log(`      Visit: http://localhost:3000${routePath === '/' ? '' : routePath}`);
  console.log('');
}

main();
